baseURL = 'https://infraspace.com.br/'
languageCode = 'pt-br'
title = 'Infra Space'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
[params.social]
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/seuusuario"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/seuusuario/"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/seuusuario"

[params.homeInfoParams]
enabled = false

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Artigos"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projetos"
    url = "/projetos/"
    weight = 3

  [[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 4